services:
  - type: web
    name: fitlife-academia
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_TURSO_DATABASE_URL
        sync: false
      - key: VITE_TURSO_AUTH_TOKEN
        sync: false
      - key: VITE_MEDIA_URL
        value: https://fabiovieitas.github.io/academia-assets
